### PR TITLE
add proxy support

### PR DESCRIPTION
**Pull request by dojiong**
support `HTTP_PROXY/HTTPS_PROXY/ALL_PROXY` environments

### CODE REVIEW

**Comment by Narsil** [comment]
Do you mind giving a bit more of motivation ?

This looks like just emulating Python `requests` which is definitely not desired.
IMHO proxy behavior belongs in user code, not manipulating env variables.

**Comment by dojiong** [comment]
I think hf-hub is not a simple request library, it's more like a tool to manage huggingface models.
It is more convenient to transparently support proxy via env in hf-hub than provide a proxy-api to downstream user.

async version will add soon(missed)

**Comment by Narsil** [comment]
Do you mind trying to make this land upstream: https://github.com/algesten/ureq/issues/322

Seems reqwest already has support: https://github.com/seanmonstar/reqwest/pull/1856

**Comment by dojiong** [comment]
> Do you mind trying to make this land upstream: [algesten/ureq#322](https://github.com/algesten/ureq/issues/322)
> 
> Seems reqwest already has support: [seanmonstar/reqwest#1856](https://github.com/seanmonstar/reqwest/pull/1856)

I'll try.

**Comment by Narsil** [comment]
TBH I didn't know this variable existed. Seems like a great way to exfiltrate traffic for any attacker..

I don't think env variables should be used for this IMHO, even if it does seems quite widespread.

**Comment by dojiong** [comment]
it's safe enough, because we use tls.

**Comment by dojiong** [comment]
upstream pr opened: algesten/ureq#649

**Comment by Narsil** [comment]
Really ? How ?

**Comment by dojiong** [comment]
If attackers can change your env, that would be the one of ways below
1. have your system's permission to write file (e.g. shell config file, scripts) or inject machine code in your process
2. you download a injected script/app to run
3. someone told you to run the command

all the ways above indicate that the attacker have got the file-write permission, then they could change your script/app to do everything, even got the root privilege.

**Comment by Narsil** [comment]
> even got the root privilege.

This is called privilege escalation, it's not an easy feat on a decently setup machine.

user space global proxy seems like a pretty bad vector to me. In any case it's definitely not the purpose of this lib to do this.

**Comment by dojiong** [comment]
> This is called privilege escalation, it's not an easy feat on a decently setup machine.

There's lots of things can do at normal user privilege, e.g. read $HF_HOME/token.

when your system is injected, that's not important your env would be changed, there be lots of ways to get/change data they want

**Comment by dojiong** [comment]
It's like a knife, just a tool. just like browser permits javascript be executed.

**Pull request closed without merging**
