### PR TITLE
Feature:  Support environment variable HF_ENDPOINT

### PR DESCRIPTION
**Pull request by ur4t**
Fix https://github.com/huggingface/hf-hub/issues/47

### CODE REVIEW

**Comment by ur4t** [comment]
More changes than #50:
- Enhance both `tokio` and `sync` clients.
- Fix test cases.

**Comment by ur4t** [comment]
@McPatate Could we continue here? #50 seems staled.

**Comment by ur4t** [comment]
@Narsil Any idea about this feature?

**Comment by sidharthrajaram** [comment]
+1 on this feature.

**Review by Qume2005 — APPROVED** [review]
nice

**Comment by Narsil** [comment]
In the end, we added support, but through explicit OPT-IN using `::from_env` initialization. https://github.com/huggingface/hf-hub/pull/85

**Pull request closed without merging**
