### PR TITLE
feat: add support for HF_ENDPOINT environment variable

### PR DESCRIPTION
**Pull request by wenhaozhao**
Supports specifying the Huggingface mirror repository through the environment, that is, HF_ENDPOINT

### CODE REVIEW

**Comment by holmofy** [comment]
@Narsil This feature is very useful for users in mainland China

**Comment by wenhaozhao** [comment]
> @Narsil This feature is very useful for users in mainland China

Yes, it is. but I don't known why they didn't accept my [PR69](https://github.com/huggingface/hf-hub/pull/69)
otherwise, you can fork my repo https://github.com/wenhaozhao/hf-hub if you like

**Comment by holmofy** [comment]
https://github.com/huggingface/hf-hub/pull/50 merged

**Comment by Narsil** [comment]
Let's keep the discussion here https://github.com/huggingface/hf-hub/issues/62
AFAIU, `HTTP(S)_PROXY` should already solve mainland china's issues, without requiring to change `HF_ENDPOINT`.

**Comment by wenhaozhao** [comment]
> Let's keep the discussion here #62 AFAIU, `HTTP(S)_PROXY` should already solve mainland china's issues, without requiring to change `HF_ENDPOINT`.

ok,

**Pull request closed without merging**
